name: bankapp

services:
  # Mainframe microservices
  security:
    build: ./mainframe/security
    container_name: security
    env_file:
      - ".env"
    ports:
      - "${SECURITY_SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - back-net
      - db-net

  user:
    build: ./mainframe/user
    container_name: users
    env_file:
      - ".env"
    ports:
      - "${USER_SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - back-net
      - db-net
  
  account:
    build: ./mainframe/account
    container_name: accounts
    env_file:
      - ".env"
    ports:
      - "${ACCOUNT_SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      user:
        condition: service_started
      mongo:
        condition: service_healthy
    networks:
      - back-net
      - db-net
  
  checking-account:
    build: ./mainframe/checking-account
    container_name: checking-accounts
    env_file:
      - ".env"
    ports:
      - "${CKACCOUNT_SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      account:
        condition: service_started
      mongo:
        condition: service_healthy
    networks:
      - back-net
      - db-net
      - queue-net
  
  dossier:
    build: ./mainframe/dossier
    container_name: dossiers
    env_file:
      - ".env"
    ports:
      - "${DOSSIER_SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      account:
        condition: service_started
      checking-account:
        condition: service_started
      mongo:
        condition: service_healthy
    networks:
      - back-net
      - db-net
  
  # Mainframe processors
  payment-processor:
    build: ./processor/payment
    container_name: payment-processor
    env_file:
      - ".env"
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - db-net
      - queue-net

  # App BFF
  bff:
    build: ./bff
    container_name: bff
    env_file:
      - ".env"
    ports:
      - "${BFF_SERVER_PORT}:${SERVER_PORT}"
    networks:
      - back-net

  # External servics
  xchanger:
    build: ./xchanger
    container_name: xchanger
    env_file:
      - ".env"
    ports:
      - "${XCHANGER_SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - back-net
      - db-net
  
  # Support services
  mongo:
    image: mongo:8.0.9
    container_name: mongo
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ./mongo/init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    #volumes:
    #  - type: bind
    #    source: /...
    #    target: /etc/mongo-data
    networks:
      - db-net
    command: mongod --quiet
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017 --quiet
      interval: 5s
      timeout: 5s
      retries: 10

  kafka:
    image: apache/kafka:4.1.0
    env_file:
      - "./kafka/config.env"
    ports:
      - "${KAFKA_PORT}:9092"
    networks:
      - queue-net

networks:
  back-net: {}
  db-net: {}
  queue-net: {}
