# Application configuration
app:
  host: "127.0.0.1"
  port: "13000"

# Mainframe server configuration
server:
  users:
    host: "user-service"
    port: "12001"
  accounts:
    host: "account-service"
    port: "12002"
