# Application configuration
app:
  host: "localhost"
  port: "13000"

# Mainframe server configuration
server:
  users:
    host: "localhost"
    port: "12001"
  accounts:
    host: "localhost"
    port: "12002"
