name: xchanger

services:
  server:
    build:
      context: .
    ports:
      - 14000:8080
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo:8.0.9
    container_name: mongo
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017 --quiet
      interval: 5s
      timeout: 5s
      retries: 10
