# Server configuration
server:
  host: "127.0.0.1"
  port: "12002"

# DB configuration
db:
  host: "mongo"
  port: "27017"
  timeout: 5

# Users server configuration
usersserver:
  host: "user-service"
  port: "12001"
